// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorawan-stack/api/qrcodegenerator.proto

package ttnpb

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QRCodeFormat struct {
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The entity fields required to generate the QR code.
	FieldMask            types.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QRCodeFormat) Reset()      { *m = QRCodeFormat{} }
func (*QRCodeFormat) ProtoMessage() {}
func (*QRCodeFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_f400aed11530ba72, []int{0}
}
func (m *QRCodeFormat) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QRCodeFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QRCodeFormat.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QRCodeFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QRCodeFormat.Merge(m, src)
}
func (m *QRCodeFormat) XXX_Size() int {
	return m.Size()
}
func (m *QRCodeFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_QRCodeFormat.DiscardUnknown(m)
}

var xxx_messageInfo_QRCodeFormat proto.InternalMessageInfo

func (m *QRCodeFormat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QRCodeFormat) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *QRCodeFormat) GetFieldMask() types.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return types.FieldMask{}
}

type QRCodeFormats struct {
	Formats              map[string]*QRCodeFormat `protobuf:"bytes,1,rep,name=formats,proto3" json:"formats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *QRCodeFormats) Reset()      { *m = QRCodeFormats{} }
func (*QRCodeFormats) ProtoMessage() {}
func (*QRCodeFormats) Descriptor() ([]byte, []int) {
	return fileDescriptor_f400aed11530ba72, []int{1}
}
func (m *QRCodeFormats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QRCodeFormats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QRCodeFormats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QRCodeFormats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QRCodeFormats.Merge(m, src)
}
func (m *QRCodeFormats) XXX_Size() int {
	return m.Size()
}
func (m *QRCodeFormats) XXX_DiscardUnknown() {
	xxx_messageInfo_QRCodeFormats.DiscardUnknown(m)
}

var xxx_messageInfo_QRCodeFormats proto.InternalMessageInfo

func (m *QRCodeFormats) GetFormats() map[string]*QRCodeFormat {
	if m != nil {
		return m.Formats
	}
	return nil
}

type GetQRCodeFormatRequest struct {
	FormatID             string   `protobuf:"bytes,1,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQRCodeFormatRequest) Reset()      { *m = GetQRCodeFormatRequest{} }
func (*GetQRCodeFormatRequest) ProtoMessage() {}
func (*GetQRCodeFormatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f400aed11530ba72, []int{2}
}
func (m *GetQRCodeFormatRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetQRCodeFormatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetQRCodeFormatRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetQRCodeFormatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQRCodeFormatRequest.Merge(m, src)
}
func (m *GetQRCodeFormatRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetQRCodeFormatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQRCodeFormatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQRCodeFormatRequest proto.InternalMessageInfo

func (m *GetQRCodeFormatRequest) GetFormatID() string {
	if m != nil {
		return m.FormatID
	}
	return ""
}

type GenerateEndDeviceQRCodeTextRequest struct {
	FormatID             string    `protobuf:"bytes,1,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	EndDevice            EndDevice `protobuf:"bytes,2,opt,name=end_device,json=endDevice,proto3" json:"end_device"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GenerateEndDeviceQRCodeTextRequest) Reset()      { *m = GenerateEndDeviceQRCodeTextRequest{} }
func (*GenerateEndDeviceQRCodeTextRequest) ProtoMessage() {}
func (*GenerateEndDeviceQRCodeTextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f400aed11530ba72, []int{3}
}
func (m *GenerateEndDeviceQRCodeTextRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenerateEndDeviceQRCodeTextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenerateEndDeviceQRCodeTextRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenerateEndDeviceQRCodeTextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateEndDeviceQRCodeTextRequest.Merge(m, src)
}
func (m *GenerateEndDeviceQRCodeTextRequest) XXX_Size() int {
	return m.Size()
}
func (m *GenerateEndDeviceQRCodeTextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateEndDeviceQRCodeTextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateEndDeviceQRCodeTextRequest proto.InternalMessageInfo

func (m *GenerateEndDeviceQRCodeTextRequest) GetFormatID() string {
	if m != nil {
		return m.FormatID
	}
	return ""
}

func (m *GenerateEndDeviceQRCodeTextRequest) GetEndDevice() EndDevice {
	if m != nil {
		return m.EndDevice
	}
	return EndDevice{}
}

type GenerateQRCodeTextResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateQRCodeTextResponse) Reset()      { *m = GenerateQRCodeTextResponse{} }
func (*GenerateQRCodeTextResponse) ProtoMessage() {}
func (*GenerateQRCodeTextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f400aed11530ba72, []int{4}
}
func (m *GenerateQRCodeTextResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenerateQRCodeTextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenerateQRCodeTextResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenerateQRCodeTextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateQRCodeTextResponse.Merge(m, src)
}
func (m *GenerateQRCodeTextResponse) XXX_Size() int {
	return m.Size()
}
func (m *GenerateQRCodeTextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateQRCodeTextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateQRCodeTextResponse proto.InternalMessageInfo

func (m *GenerateQRCodeTextResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type GenerateEndDeviceQRCodeImageRequest struct {
	FormatID             string    `protobuf:"bytes,1,opt,name=format_id,json=formatId,proto3" json:"format_id,omitempty"`
	EndDevice            EndDevice `protobuf:"bytes,2,opt,name=end_device,json=endDevice,proto3" json:"end_device"`
	ImageSize            uint32    `protobuf:"varint,3,opt,name=image_size,json=imageSize,proto3" json:"image_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GenerateEndDeviceQRCodeImageRequest) Reset()      { *m = GenerateEndDeviceQRCodeImageRequest{} }
func (*GenerateEndDeviceQRCodeImageRequest) ProtoMessage() {}
func (*GenerateEndDeviceQRCodeImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f400aed11530ba72, []int{5}
}
func (m *GenerateEndDeviceQRCodeImageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenerateEndDeviceQRCodeImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenerateEndDeviceQRCodeImageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenerateEndDeviceQRCodeImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateEndDeviceQRCodeImageRequest.Merge(m, src)
}
func (m *GenerateEndDeviceQRCodeImageRequest) XXX_Size() int {
	return m.Size()
}
func (m *GenerateEndDeviceQRCodeImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateEndDeviceQRCodeImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateEndDeviceQRCodeImageRequest proto.InternalMessageInfo

func (m *GenerateEndDeviceQRCodeImageRequest) GetFormatID() string {
	if m != nil {
		return m.FormatID
	}
	return ""
}

func (m *GenerateEndDeviceQRCodeImageRequest) GetEndDevice() EndDevice {
	if m != nil {
		return m.EndDevice
	}
	return EndDevice{}
}

func (m *GenerateEndDeviceQRCodeImageRequest) GetImageSize() uint32 {
	if m != nil {
		return m.ImageSize
	}
	return 0
}

type GenerateQRCodeImageResponse struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// QR code in PNG format.
	Image                []byte   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateQRCodeImageResponse) Reset()      { *m = GenerateQRCodeImageResponse{} }
func (*GenerateQRCodeImageResponse) ProtoMessage() {}
func (*GenerateQRCodeImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f400aed11530ba72, []int{6}
}
func (m *GenerateQRCodeImageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenerateQRCodeImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenerateQRCodeImageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenerateQRCodeImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateQRCodeImageResponse.Merge(m, src)
}
func (m *GenerateQRCodeImageResponse) XXX_Size() int {
	return m.Size()
}
func (m *GenerateQRCodeImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateQRCodeImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateQRCodeImageResponse proto.InternalMessageInfo

func (m *GenerateQRCodeImageResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *GenerateQRCodeImageResponse) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func init() {
	proto.RegisterType((*QRCodeFormat)(nil), "ttn.lorawan.v3.QRCodeFormat")
	golang_proto.RegisterType((*QRCodeFormat)(nil), "ttn.lorawan.v3.QRCodeFormat")
	proto.RegisterType((*QRCodeFormats)(nil), "ttn.lorawan.v3.QRCodeFormats")
	golang_proto.RegisterType((*QRCodeFormats)(nil), "ttn.lorawan.v3.QRCodeFormats")
	proto.RegisterMapType((map[string]*QRCodeFormat)(nil), "ttn.lorawan.v3.QRCodeFormats.FormatsEntry")
	golang_proto.RegisterMapType((map[string]*QRCodeFormat)(nil), "ttn.lorawan.v3.QRCodeFormats.FormatsEntry")
	proto.RegisterType((*GetQRCodeFormatRequest)(nil), "ttn.lorawan.v3.GetQRCodeFormatRequest")
	golang_proto.RegisterType((*GetQRCodeFormatRequest)(nil), "ttn.lorawan.v3.GetQRCodeFormatRequest")
	proto.RegisterType((*GenerateEndDeviceQRCodeTextRequest)(nil), "ttn.lorawan.v3.GenerateEndDeviceQRCodeTextRequest")
	golang_proto.RegisterType((*GenerateEndDeviceQRCodeTextRequest)(nil), "ttn.lorawan.v3.GenerateEndDeviceQRCodeTextRequest")
	proto.RegisterType((*GenerateQRCodeTextResponse)(nil), "ttn.lorawan.v3.GenerateQRCodeTextResponse")
	golang_proto.RegisterType((*GenerateQRCodeTextResponse)(nil), "ttn.lorawan.v3.GenerateQRCodeTextResponse")
	proto.RegisterType((*GenerateEndDeviceQRCodeImageRequest)(nil), "ttn.lorawan.v3.GenerateEndDeviceQRCodeImageRequest")
	golang_proto.RegisterType((*GenerateEndDeviceQRCodeImageRequest)(nil), "ttn.lorawan.v3.GenerateEndDeviceQRCodeImageRequest")
	proto.RegisterType((*GenerateQRCodeImageResponse)(nil), "ttn.lorawan.v3.GenerateQRCodeImageResponse")
	golang_proto.RegisterType((*GenerateQRCodeImageResponse)(nil), "ttn.lorawan.v3.GenerateQRCodeImageResponse")
}

func init() {
	proto.RegisterFile("lorawan-stack/api/qrcodegenerator.proto", fileDescriptor_f400aed11530ba72)
}
func init() {
	golang_proto.RegisterFile("lorawan-stack/api/qrcodegenerator.proto", fileDescriptor_f400aed11530ba72)
}

var fileDescriptor_f400aed11530ba72 = []byte{
	// 942 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0x3d, 0x6c, 0xdb, 0x46,
	0x14, 0xc7, 0x79, 0xfa, 0xa8, 0xad, 0x93, 0xdc, 0x06, 0x87, 0x22, 0x60, 0x68, 0xf7, 0x6c, 0xb0,
	0x6e, 0xaa, 0xa8, 0x16, 0x19, 0xc8, 0x40, 0xd1, 0x7a, 0x31, 0xca, 0xc6, 0x36, 0x0c, 0x34, 0x40,
	0xcb, 0x76, 0x28, 0x1a, 0xa4, 0x06, 0x2d, 0x9e, 0x69, 0x56, 0x12, 0x8f, 0x21, 0xcf, 0x8a, 0xe5,
	0x20, 0x40, 0xd0, 0x2e, 0x41, 0xa7, 0x02, 0xed, 0x10, 0x74, 0x28, 0x82, 0x4e, 0x19, 0x33, 0x7a,
	0x2a, 0x32, 0x74, 0xf0, 0x18, 0xa0, 0x4b, 0xa6, 0x20, 0x22, 0x3b, 0x78, 0xcc, 0x52, 0x20, 0xd0,
	0x54, 0xe8, 0x78, 0x74, 0xf4, 0x61, 0xab, 0x59, 0x0a, 0x64, 0xd2, 0x1d, 0xdf, 0xbb, 0x77, 0xbf,
	0xf7, 0xbf, 0xf7, 0x9e, 0xe0, 0xfb, 0x4d, 0x1a, 0x58, 0x37, 0x2d, 0xaf, 0x1a, 0x32, 0xab, 0xde,
	0xd0, 0x2d, 0xdf, 0xd5, 0x6f, 0x04, 0x75, 0x6a, 0x13, 0x87, 0x78, 0x24, 0xb0, 0x18, 0x0d, 0x34,
	0x3f, 0xa0, 0x8c, 0xa2, 0x37, 0x19, 0xf3, 0x34, 0xe1, 0xac, 0xb5, 0x97, 0x95, 0x4f, 0x1c, 0x97,
	0xed, 0xee, 0x6d, 0x6b, 0x75, 0xda, 0xd2, 0x89, 0xd7, 0xa6, 0x1d, 0x3f, 0xa0, 0xfb, 0x1d, 0x9d,
	0x3b, 0xd7, 0xab, 0x0e, 0xf1, 0xaa, 0x6d, 0xab, 0xe9, 0xda, 0x16, 0x23, 0xfa, 0xd8, 0x22, 0x09,
	0xa9, 0x54, 0x07, 0x42, 0x38, 0xd4, 0xa1, 0xc9, 0xe1, 0xed, 0xbd, 0x1d, 0xbe, 0xe3, 0x1b, 0xbe,
	0x12, 0xee, 0x73, 0x0e, 0xa5, 0x4e, 0x93, 0x70, 0x46, 0xcb, 0xf3, 0x28, 0xb3, 0x98, 0x4b, 0xbd,
	0x50, 0x58, 0x67, 0x85, 0xf5, 0x24, 0x06, 0x69, 0xf9, 0xac, 0x23, 0x8c, 0x0b, 0xa3, 0xc6, 0x1d,
	0x97, 0x34, 0xed, 0xad, 0x96, 0x15, 0x36, 0x84, 0x87, 0x3a, 0xae, 0x03, 0xf1, 0xec, 0x2d, 0x9b,
	0xb4, 0xdd, 0xba, 0xe0, 0x55, 0x7f, 0x03, 0xb0, 0xf4, 0x85, 0xf9, 0x29, 0xb5, 0xc9, 0x3a, 0x0d,
	0x5a, 0x16, 0x43, 0xb3, 0x30, 0xe7, 0x59, 0x2d, 0x22, 0x83, 0x05, 0x50, 0x2e, 0x18, 0x53, 0x3d,
	0x23, 0x17, 0x64, 0x64, 0xdb, 0xe4, 0x1f, 0x51, 0x05, 0x16, 0x6d, 0x12, 0xd6, 0x03, 0xd7, 0xef,
	0x63, 0xca, 0x19, 0xee, 0x33, 0xdd, 0x33, 0xf2, 0x41, 0x56, 0x3e, 0x02, 0xe6, 0xa0, 0x11, 0xad,
	0x42, 0xf8, 0x92, 0x48, 0xce, 0x2e, 0x80, 0x72, 0xb1, 0xa6, 0x68, 0x09, 0xb4, 0x96, 0x42, 0x6b,
	0xeb, 0x7d, 0x97, 0xab, 0x56, 0xd8, 0x30, 0x72, 0x47, 0x4f, 0xe7, 0x25, 0xb3, 0xb0, 0x93, 0x7e,
	0x58, 0xc9, 0x1d, 0xde, 0x9f, 0x97, 0xd4, 0x18, 0xc0, 0x99, 0x41, 0xc0, 0x10, 0x05, 0x70, 0x6a,
	0x27, 0x59, 0xca, 0x60, 0x21, 0x5b, 0x2e, 0xd6, 0x2a, 0xda, 0xf0, 0x3b, 0x6a, 0x43, 0xfe, 0x9a,
	0xf8, 0x5d, 0xf3, 0x58, 0xd0, 0x31, 0x96, 0x7a, 0xc6, 0xa5, 0x5f, 0xc1, 0x45, 0x75, 0x31, 0x50,
	0xe5, 0xc5, 0x1a, 0xfe, 0xf6, 0x9a, 0x55, 0x3d, 0xb8, 0x5c, 0xfd, 0xf8, 0x7a, 0x79, 0x75, 0xe5,
	0x5a, 0xf5, 0xfa, 0x6a, 0xba, 0xbd, 0x74, 0xab, 0xb6, 0x74, 0x7b, 0xd1, 0x4c, 0x2f, 0x52, 0xbe,
	0x86, 0xa5, 0xc1, 0x30, 0xe8, 0x1c, 0xcc, 0x36, 0x48, 0x27, 0x11, 0xc9, 0xec, 0x2f, 0x51, 0x0d,
	0xe6, 0xdb, 0x56, 0x73, 0x8f, 0x70, 0x51, 0x8a, 0xb5, 0xb9, 0x49, 0x4c, 0x66, 0xe2, 0xba, 0x92,
	0xf9, 0x08, 0x88, 0x2c, 0x7d, 0x78, 0x7e, 0x83, 0xb0, 0x21, 0x1f, 0x72, 0x63, 0x8f, 0x84, 0x0c,
	0x7d, 0x0e, 0x0b, 0x09, 0xc4, 0x96, 0x6b, 0x8b, 0x47, 0x59, 0xee, 0x19, 0xaf, 0x84, 0x1f, 0x3d,
	0x9d, 0x9f, 0x4e, 0x82, 0x6d, 0x5e, 0x31, 0xa7, 0x93, 0x28, 0x9b, 0xb6, 0xb8, 0xf1, 0x4f, 0x00,
	0xd5, 0x8d, 0xa4, 0x1f, 0xc8, 0x9a, 0x67, 0x5f, 0xe1, 0x45, 0x91, 0x00, 0x7c, 0x45, 0xf6, 0xff,
	0xbf, 0xeb, 0xd1, 0x3a, 0x84, 0x2f, 0xab, 0x50, 0xa8, 0x75, 0x61, 0x54, 0xad, 0x13, 0x22, 0xa3,
	0xd4, 0x33, 0xf2, 0x3f, 0x82, 0xcc, 0x39, 0x90, 0x94, 0x07, 0x49, 0x0d, 0x22, 0x8d, 0x0f, 0xa1,
	0x92, 0x66, 0x31, 0x08, 0x1f, 0xfa, 0xd4, 0x0b, 0x09, 0x42, 0x30, 0xc7, 0xc8, 0x3e, 0x13, 0xef,
	0xc4, 0xd7, 0xe2, 0xdc, 0x3f, 0x00, 0xbe, 0x7b, 0x46, 0xfa, 0x9b, 0x2d, 0xcb, 0x21, 0xaf, 0x7d,
	0xfe, 0x48, 0x83, 0xd0, 0xed, 0x93, 0x6e, 0x85, 0xee, 0x01, 0xe1, 0xfd, 0x35, 0x63, 0xbc, 0xd5,
	0x33, 0x72, 0x95, 0x4c, 0x19, 0xf6, 0x8c, 0x7c, 0x25, 0x2b, 0x1f, 0x4f, 0x99, 0x05, 0xee, 0xf2,
	0xa5, 0x7b, 0x90, 0xea, 0x75, 0x15, 0xce, 0x0e, 0xeb, 0x25, 0xb2, 0x3d, 0x5b, 0x30, 0xf4, 0x36,
	0xcc, 0xf3, 0x28, 0x9c, 0xb5, 0x64, 0x26, 0x9b, 0x24, 0x5c, 0xed, 0x8f, 0x1c, 0x94, 0x47, 0xe4,
	0xdb, 0x48, 0x87, 0x2c, 0xfa, 0x01, 0xc0, 0xc2, 0x06, 0x61, 0x62, 0xb0, 0x5c, 0x1c, 0xcd, 0xf1,
	0xf4, 0x82, 0x57, 0x26, 0x76, 0x8e, 0x7a, 0xf9, 0xfb, 0xbf, 0xfe, 0xfe, 0x39, 0x53, 0x41, 0x65,
	0x31, 0xd2, 0xc3, 0xfe, 0x48, 0xab, 0x26, 0x62, 0x86, 0xba, 0x68, 0x57, 0xfd, 0xd6, 0xc9, 0x9b,
	0xdd, 0x46, 0xdf, 0xc1, 0xe2, 0x67, 0x6e, 0xc8, 0xd2, 0xe9, 0x71, 0x7e, 0x6c, 0x04, 0xad, 0xf5,
	0x87, 0xaa, 0xf2, 0xce, 0xc4, 0x21, 0xa2, 0x2e, 0xf2, 0x7b, 0x31, 0x9a, 0x9b, 0x74, 0x2f, 0xfa,
	0x05, 0xc0, 0x52, 0x2a, 0x6f, 0xbf, 0x10, 0x51, 0x6d, 0x3c, 0xe9, 0xff, 0x6a, 0x39, 0xa5, 0x72,
	0xd6, 0x99, 0xf1, 0x02, 0x4f, 0xb1, 0xd4, 0x0b, 0xa7, 0x62, 0xf1, 0x7a, 0x07, 0x15, 0x74, 0x0f,
	0xc0, 0x99, 0x34, 0x08, 0x7f, 0x6f, 0xb4, 0xfc, 0x8a, 0x5c, 0x83, 0xbd, 0xa0, 0x7c, 0x30, 0x19,
	0x6c, 0xa8, 0x92, 0xd4, 0xf7, 0x38, 0xd9, 0xbc, 0xaa, 0x9c, 0x4a, 0x96, 0xd4, 0x10, 0xa8, 0x18,
	0xbf, 0x83, 0xa3, 0x2e, 0x06, 0x8f, 0xbb, 0x18, 0x3c, 0xe9, 0x62, 0xe9, 0x59, 0x17, 0x4b, 0xc7,
	0x5d, 0x2c, 0x3d, 0xef, 0x62, 0xe9, 0x45, 0x17, 0x83, 0x3b, 0x11, 0x06, 0x77, 0x23, 0x2c, 0x3d,
	0x88, 0x30, 0x78, 0x18, 0x61, 0xe9, 0x30, 0xc2, 0xd2, 0xa3, 0x08, 0x4b, 0x47, 0x11, 0x06, 0x8f,
	0x23, 0x0c, 0x9e, 0x44, 0x58, 0x7a, 0x16, 0x61, 0x70, 0x1c, 0x61, 0xe9, 0x79, 0x84, 0xc1, 0x8b,
	0x08, 0x4b, 0x77, 0x62, 0x2c, 0xdd, 0x8d, 0x31, 0xf8, 0x29, 0xc6, 0xd2, 0xbd, 0x18, 0x83, 0xfb,
	0x31, 0x96, 0x1e, 0xc4, 0x58, 0x7a, 0x18, 0x63, 0x70, 0x18, 0x63, 0xf0, 0x28, 0xc6, 0xe0, 0x9b,
	0x25, 0x87, 0x6a, 0x6c, 0x97, 0xb0, 0x5d, 0xd7, 0x73, 0x42, 0xcd, 0x23, 0xec, 0x26, 0x0d, 0x1a,
	0xfa, 0xf0, 0xff, 0xa5, 0xdf, 0x70, 0x74, 0xc6, 0x3c, 0x7f, 0x7b, 0xfb, 0x0d, 0x5e, 0x2b, 0xcb,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x81, 0x35, 0xa3, 0x59, 0x08, 0x00, 0x00,
}

func (this *QRCodeFormat) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QRCodeFormat)
	if !ok {
		that2, ok := that.(QRCodeFormat)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if !this.FieldMask.Equal(&that1.FieldMask) {
		return false
	}
	return true
}
func (this *QRCodeFormats) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QRCodeFormats)
	if !ok {
		that2, ok := that.(QRCodeFormats)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Formats) != len(that1.Formats) {
		return false
	}
	for i := range this.Formats {
		if !this.Formats[i].Equal(that1.Formats[i]) {
			return false
		}
	}
	return true
}
func (this *GetQRCodeFormatRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetQRCodeFormatRequest)
	if !ok {
		that2, ok := that.(GetQRCodeFormatRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FormatID != that1.FormatID {
		return false
	}
	return true
}
func (this *GenerateEndDeviceQRCodeTextRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenerateEndDeviceQRCodeTextRequest)
	if !ok {
		that2, ok := that.(GenerateEndDeviceQRCodeTextRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FormatID != that1.FormatID {
		return false
	}
	if !this.EndDevice.Equal(&that1.EndDevice) {
		return false
	}
	return true
}
func (this *GenerateQRCodeTextResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenerateQRCodeTextResponse)
	if !ok {
		that2, ok := that.(GenerateQRCodeTextResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Text != that1.Text {
		return false
	}
	return true
}
func (this *GenerateEndDeviceQRCodeImageRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenerateEndDeviceQRCodeImageRequest)
	if !ok {
		that2, ok := that.(GenerateEndDeviceQRCodeImageRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FormatID != that1.FormatID {
		return false
	}
	if !this.EndDevice.Equal(&that1.EndDevice) {
		return false
	}
	if this.ImageSize != that1.ImageSize {
		return false
	}
	return true
}
func (this *GenerateQRCodeImageResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenerateQRCodeImageResponse)
	if !ok {
		that2, ok := that.(GenerateQRCodeImageResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Text != that1.Text {
		return false
	}
	if !bytes.Equal(this.Image, that1.Image) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EndDeviceQRCodeGeneratorClient is the client API for EndDeviceQRCodeGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EndDeviceQRCodeGeneratorClient interface {
	// Return the QR code format.
	GetFormat(ctx context.Context, in *GetQRCodeFormatRequest, opts ...grpc.CallOption) (*QRCodeFormat, error)
	// Returns the supported formats.
	ListFormats(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*QRCodeFormats, error)
	// Generates the text value of the QR code.
	GenerateText(ctx context.Context, in *GenerateEndDeviceQRCodeTextRequest, opts ...grpc.CallOption) (*GenerateQRCodeTextResponse, error)
	// Generates a QR code image in PNG format.
	GenerateImage(ctx context.Context, in *GenerateEndDeviceQRCodeImageRequest, opts ...grpc.CallOption) (*GenerateQRCodeImageResponse, error)
}

type endDeviceQRCodeGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewEndDeviceQRCodeGeneratorClient(cc *grpc.ClientConn) EndDeviceQRCodeGeneratorClient {
	return &endDeviceQRCodeGeneratorClient{cc}
}

func (c *endDeviceQRCodeGeneratorClient) GetFormat(ctx context.Context, in *GetQRCodeFormatRequest, opts ...grpc.CallOption) (*QRCodeFormat, error) {
	out := new(QRCodeFormat)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.EndDeviceQRCodeGenerator/GetFormat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endDeviceQRCodeGeneratorClient) ListFormats(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*QRCodeFormats, error) {
	out := new(QRCodeFormats)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.EndDeviceQRCodeGenerator/ListFormats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endDeviceQRCodeGeneratorClient) GenerateText(ctx context.Context, in *GenerateEndDeviceQRCodeTextRequest, opts ...grpc.CallOption) (*GenerateQRCodeTextResponse, error) {
	out := new(GenerateQRCodeTextResponse)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.EndDeviceQRCodeGenerator/GenerateText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endDeviceQRCodeGeneratorClient) GenerateImage(ctx context.Context, in *GenerateEndDeviceQRCodeImageRequest, opts ...grpc.CallOption) (*GenerateQRCodeImageResponse, error) {
	out := new(GenerateQRCodeImageResponse)
	err := c.cc.Invoke(ctx, "/ttn.lorawan.v3.EndDeviceQRCodeGenerator/GenerateImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndDeviceQRCodeGeneratorServer is the server API for EndDeviceQRCodeGenerator service.
type EndDeviceQRCodeGeneratorServer interface {
	// Return the QR code format.
	GetFormat(context.Context, *GetQRCodeFormatRequest) (*QRCodeFormat, error)
	// Returns the supported formats.
	ListFormats(context.Context, *types.Empty) (*QRCodeFormats, error)
	// Generates the text value of the QR code.
	GenerateText(context.Context, *GenerateEndDeviceQRCodeTextRequest) (*GenerateQRCodeTextResponse, error)
	// Generates a QR code image in PNG format.
	GenerateImage(context.Context, *GenerateEndDeviceQRCodeImageRequest) (*GenerateQRCodeImageResponse, error)
}

// UnimplementedEndDeviceQRCodeGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedEndDeviceQRCodeGeneratorServer struct {
}

func (*UnimplementedEndDeviceQRCodeGeneratorServer) GetFormat(ctx context.Context, req *GetQRCodeFormatRequest) (*QRCodeFormat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFormat not implemented")
}
func (*UnimplementedEndDeviceQRCodeGeneratorServer) ListFormats(ctx context.Context, req *types.Empty) (*QRCodeFormats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFormats not implemented")
}
func (*UnimplementedEndDeviceQRCodeGeneratorServer) GenerateText(ctx context.Context, req *GenerateEndDeviceQRCodeTextRequest) (*GenerateQRCodeTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateText not implemented")
}
func (*UnimplementedEndDeviceQRCodeGeneratorServer) GenerateImage(ctx context.Context, req *GenerateEndDeviceQRCodeImageRequest) (*GenerateQRCodeImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateImage not implemented")
}

func RegisterEndDeviceQRCodeGeneratorServer(s *grpc.Server, srv EndDeviceQRCodeGeneratorServer) {
	s.RegisterService(&_EndDeviceQRCodeGenerator_serviceDesc, srv)
}

func _EndDeviceQRCodeGenerator_GetFormat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQRCodeFormatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndDeviceQRCodeGeneratorServer).GetFormat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.EndDeviceQRCodeGenerator/GetFormat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndDeviceQRCodeGeneratorServer).GetFormat(ctx, req.(*GetQRCodeFormatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndDeviceQRCodeGenerator_ListFormats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndDeviceQRCodeGeneratorServer).ListFormats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.EndDeviceQRCodeGenerator/ListFormats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndDeviceQRCodeGeneratorServer).ListFormats(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndDeviceQRCodeGenerator_GenerateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEndDeviceQRCodeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndDeviceQRCodeGeneratorServer).GenerateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.EndDeviceQRCodeGenerator/GenerateText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndDeviceQRCodeGeneratorServer).GenerateText(ctx, req.(*GenerateEndDeviceQRCodeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndDeviceQRCodeGenerator_GenerateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEndDeviceQRCodeImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndDeviceQRCodeGeneratorServer).GenerateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttn.lorawan.v3.EndDeviceQRCodeGenerator/GenerateImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndDeviceQRCodeGeneratorServer).GenerateImage(ctx, req.(*GenerateEndDeviceQRCodeImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EndDeviceQRCodeGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ttn.lorawan.v3.EndDeviceQRCodeGenerator",
	HandlerType: (*EndDeviceQRCodeGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFormat",
			Handler:    _EndDeviceQRCodeGenerator_GetFormat_Handler,
		},
		{
			MethodName: "ListFormats",
			Handler:    _EndDeviceQRCodeGenerator_ListFormats_Handler,
		},
		{
			MethodName: "GenerateText",
			Handler:    _EndDeviceQRCodeGenerator_GenerateText_Handler,
		},
		{
			MethodName: "GenerateImage",
			Handler:    _EndDeviceQRCodeGenerator_GenerateImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorawan-stack/api/qrcodegenerator.proto",
}

func (m *QRCodeFormat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QRCodeFormat) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QRCodeFormat) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.FieldMask.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QRCodeFormats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QRCodeFormats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QRCodeFormats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Formats) > 0 {
		for k := range m.Formats {
			v := m.Formats[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintQrcodegenerator(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintQrcodegenerator(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetQRCodeFormatRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetQRCodeFormatRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetQRCodeFormatRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FormatID) > 0 {
		i -= len(m.FormatID)
		copy(dAtA[i:], m.FormatID)
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(m.FormatID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenerateEndDeviceQRCodeTextRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenerateEndDeviceQRCodeTextRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenerateEndDeviceQRCodeTextRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.EndDevice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.FormatID) > 0 {
		i -= len(m.FormatID)
		copy(dAtA[i:], m.FormatID)
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(m.FormatID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenerateQRCodeTextResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenerateQRCodeTextResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenerateQRCodeTextResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenerateEndDeviceQRCodeImageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenerateEndDeviceQRCodeImageRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenerateEndDeviceQRCodeImageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ImageSize != 0 {
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(m.ImageSize))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.EndDevice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.FormatID) > 0 {
		i -= len(m.FormatID)
		copy(dAtA[i:], m.FormatID)
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(m.FormatID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenerateQRCodeImageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenerateQRCodeImageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenerateQRCodeImageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintQrcodegenerator(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQrcodegenerator(dAtA []byte, offset int, v uint64) int {
	offset -= sovQrcodegenerator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QRCodeFormat) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQrcodegenerator(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovQrcodegenerator(uint64(l))
	}
	l = m.FieldMask.Size()
	n += 1 + l + sovQrcodegenerator(uint64(l))
	return n
}

func (m *QRCodeFormats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Formats) > 0 {
		for k, v := range m.Formats {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovQrcodegenerator(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovQrcodegenerator(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovQrcodegenerator(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *GetQRCodeFormatRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FormatID)
	if l > 0 {
		n += 1 + l + sovQrcodegenerator(uint64(l))
	}
	return n
}

func (m *GenerateEndDeviceQRCodeTextRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FormatID)
	if l > 0 {
		n += 1 + l + sovQrcodegenerator(uint64(l))
	}
	l = m.EndDevice.Size()
	n += 1 + l + sovQrcodegenerator(uint64(l))
	return n
}

func (m *GenerateQRCodeTextResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovQrcodegenerator(uint64(l))
	}
	return n
}

func (m *GenerateEndDeviceQRCodeImageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FormatID)
	if l > 0 {
		n += 1 + l + sovQrcodegenerator(uint64(l))
	}
	l = m.EndDevice.Size()
	n += 1 + l + sovQrcodegenerator(uint64(l))
	if m.ImageSize != 0 {
		n += 1 + sovQrcodegenerator(uint64(m.ImageSize))
	}
	return n
}

func (m *GenerateQRCodeImageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovQrcodegenerator(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovQrcodegenerator(uint64(l))
	}
	return n
}

func sovQrcodegenerator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQrcodegenerator(x uint64) (n int) {
	return sovQrcodegenerator((x << 1) ^ uint64((int64(x) >> 63)))
}
func (this *QRCodeFormat) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&QRCodeFormat{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`FieldMask:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.FieldMask), "FieldMask", "types.FieldMask", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *QRCodeFormats) String() string {
	if this == nil {
		return "nil"
	}
	keysForFormats := make([]string, 0, len(this.Formats))
	for k := range this.Formats {
		keysForFormats = append(keysForFormats, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForFormats)
	mapStringForFormats := "map[string]*QRCodeFormat{"
	for _, k := range keysForFormats {
		mapStringForFormats += fmt.Sprintf("%v: %v,", k, this.Formats[k])
	}
	mapStringForFormats += "}"
	s := strings.Join([]string{`&QRCodeFormats{`,
		`Formats:` + mapStringForFormats + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetQRCodeFormatRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetQRCodeFormatRequest{`,
		`FormatID:` + fmt.Sprintf("%v", this.FormatID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GenerateEndDeviceQRCodeTextRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GenerateEndDeviceQRCodeTextRequest{`,
		`FormatID:` + fmt.Sprintf("%v", this.FormatID) + `,`,
		`EndDevice:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.EndDevice), "EndDevice", "EndDevice", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GenerateQRCodeTextResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GenerateQRCodeTextResponse{`,
		`Text:` + fmt.Sprintf("%v", this.Text) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GenerateEndDeviceQRCodeImageRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GenerateEndDeviceQRCodeImageRequest{`,
		`FormatID:` + fmt.Sprintf("%v", this.FormatID) + `,`,
		`EndDevice:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.EndDevice), "EndDevice", "EndDevice", 1), `&`, ``, 1) + `,`,
		`ImageSize:` + fmt.Sprintf("%v", this.ImageSize) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GenerateQRCodeImageResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GenerateQRCodeImageResponse{`,
		`Text:` + fmt.Sprintf("%v", this.Text) + `,`,
		`Image:` + fmt.Sprintf("%v", this.Image) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringQrcodegenerator(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *QRCodeFormat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQrcodegenerator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QRCodeFormat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QRCodeFormat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldMask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FieldMask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQrcodegenerator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QRCodeFormats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQrcodegenerator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QRCodeFormats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QRCodeFormats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Formats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Formats == nil {
				m.Formats = make(map[string]*QRCodeFormat)
			}
			var mapkey string
			var mapvalue *QRCodeFormat
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQrcodegenerator
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQrcodegenerator
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthQrcodegenerator
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthQrcodegenerator
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQrcodegenerator
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthQrcodegenerator
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthQrcodegenerator
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &QRCodeFormat{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipQrcodegenerator(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthQrcodegenerator
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Formats[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQrcodegenerator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetQRCodeFormatRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQrcodegenerator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetQRCodeFormatRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetQRCodeFormatRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FormatID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FormatID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQrcodegenerator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenerateEndDeviceQRCodeTextRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQrcodegenerator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenerateEndDeviceQRCodeTextRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenerateEndDeviceQRCodeTextRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FormatID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FormatID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndDevice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EndDevice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQrcodegenerator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenerateQRCodeTextResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQrcodegenerator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenerateQRCodeTextResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenerateQRCodeTextResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQrcodegenerator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenerateEndDeviceQRCodeImageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQrcodegenerator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenerateEndDeviceQRCodeImageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenerateEndDeviceQRCodeImageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FormatID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FormatID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndDevice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EndDevice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageSize", wireType)
			}
			m.ImageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ImageSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQrcodegenerator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenerateQRCodeImageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQrcodegenerator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenerateQRCodeImageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenerateQRCodeImageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = append(m.Image[:0], dAtA[iNdEx:postIndex]...)
			if m.Image == nil {
				m.Image = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQrcodegenerator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQrcodegenerator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQrcodegenerator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQrcodegenerator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQrcodegenerator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQrcodegenerator
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthQrcodegenerator
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowQrcodegenerator
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipQrcodegenerator(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthQrcodegenerator
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthQrcodegenerator = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQrcodegenerator   = fmt.Errorf("proto: integer overflow")
)
